[proxy]
nso-test_proxy ansible_host=10.0.0.181 ansible_user=ubuntu ansible_ssh_private_key_file=nso_key

[service_nodes]
nso-test_service1 ansible_host=10.0.0.217 ansible_user=ubuntu ansible_ssh_private_key_file=nso_key
nso-test_service2 ansible_host=10.0.0.229 ansible_user=ubuntu ansible_ssh_private_key_file=nso_key

[all:vars]
ansible_python_interpreter=/usr/bin/python3
