# Listen on localhost
agentAddress udp:127.0.0.1:161

# System description
sysdescr "Service Node for NSO Project"

# Contact and location
syscontact Hareesh Satyendra
syslocation "Data Center"

# Read-only community
rocommunity public localhost

# Enable monitoring of system resources
load 12 14 14